var 20260528165532__AddUniqueIndexesMaterialsAndCuerdas_8cs =
[
    [ "BackEncordados.Migrations.Materials.AddUniqueIndexesMaterialsAndCuerdas", "classBackEncordados_1_1Migrations_1_1Materials_1_1AddUniqueIndexesMaterialsAndCuerdas.html", "classBackEncordados_1_1Migrations_1_1Materials_1_1AddUniqueIndexesMaterialsAndCuerdas" ]
];