var hierarchy =
[
    [ "AbstractValidator", null, [
      [ "BackEncordados.Materials.Validator.Materials.MaterialPatchValidator", "classBackEncordados_1_1Materials_1_1Validator_1_1Materials_1_1MaterialPatchValidator.html", null ],
      [ "BackEncordados.Materials.Validator.Materials.MaterialRequestValidator", "classBackEncordados_1_1Materials_1_1Validator_1_1Materials_1_1MaterialRequestValidator.html", null ],
      [ "BackEncordados.Materials.Validator.Strings.CuerdaPatchValidator", "classBackEncordados_1_1Materials_1_1Validator_1_1Strings_1_1CuerdaPatchValidator.html", null ],
      [ "BackEncordados.Materials.Validator.Strings.CuerdaRequestValidator", "classBackEncordados_1_1Materials_1_1Validator_1_1Strings_1_1CuerdaRequestValidator.html", null ],
      [ "BackEncordados.Purchased.Validator.PedidoLineaRequestValidator", "classBackEncordados_1_1Purchased_1_1Validator_1_1PedidoLineaRequestValidator.html", null ],
      [ "BackEncordados.Purchased.Validator.PurchasedPatchValidator", "classBackEncordados_1_1Purchased_1_1Validator_1_1PurchasedPatchValidator.html", null ],
      [ "BackEncordados.Purchased.Validator.PurchasedRequestValidator", "classBackEncordados_1_1Purchased_1_1Validator_1_1PurchasedRequestValidator.html", null ],
      [ "BackEncordados.Purchased.Validator.StringSetupPatchValidator", "classBackEncordados_1_1Purchased_1_1Validator_1_1StringSetupPatchValidator.html", null ],
      [ "BackEncordados.Purchased.Validator.StringSetupRequestValidator", "classBackEncordados_1_1Purchased_1_1Validator_1_1StringSetupRequestValidator.html", null ],
      [ "BackEncordados.Usuarios.Validator.ChangeRoleRequestDtoValidator", "classBackEncordados_1_1Usuarios_1_1Validator_1_1ChangeRoleRequestDtoValidator.html", null ],
      [ "BackEncordados.Usuarios.Validator.UserRequestDtoValidator", "classBackEncordados_1_1Usuarios_1_1Validator_1_1UserRequestDtoValidator.html", null ]
    ] ],
    [ "ActionFilterAttribute", null, [
      [ "BackEncordados.Common.Utils.TransactionalAttribute", "classBackEncordados_1_1Common_1_1Utils_1_1TransactionalAttribute.html", null ]
    ] ],
    [ "BackEncordados.Infraestructure.AppOptions", "classBackEncordados_1_1Infraestructure_1_1AppOptions.html", null ],
    [ "TestEncordados.Integration.Api.AppStartupTests", "classTestEncordados_1_1Integration_1_1Api_1_1AppStartupTests.html", null ],
    [ "TestEncordados.Unit.AuthController.AuthControllerTests", "classTestEncordados_1_1Unit_1_1AuthController_1_1AuthControllerTests.html", null ],
    [ "TestEncordados.Unit.Errors.AuthErrorTests", "classTestEncordados_1_1Unit_1_1Errors_1_1AuthErrorTests.html", null ],
    [ "TestEncordados.Unit.Services.AuthService.AuthServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1AuthService_1_1AuthServiceTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Cache.CacheKeysTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cache_1_1CacheKeysTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Cache.CacheServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cache_1_1CacheServiceTests.html", null ],
    [ "BackEncordados.Usuarios.Dto.ChangePasswordRequestDto", "classBackEncordados_1_1Usuarios_1_1Dto_1_1ChangePasswordRequestDto.html", null ],
    [ "TestEncordados.Unit.Validators.Usuarios.ChangeRoleRequestDtoValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Usuarios_1_1ChangeRoleRequestDtoValidatorTests.html", null ],
    [ "TestEncordados.Unit.Common.Exceptions.CloudinaryExceptionTests", "classTestEncordados_1_1Unit_1_1Common_1_1Exceptions_1_1CloudinaryExceptionTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Cloudinary.CloudinaryServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cloudinary_1_1CloudinaryServiceTests.html", null ],
    [ "BackEncordados.Common.Service.Cloudinary.CloudinaryUploadResult", "classBackEncordados_1_1Common_1_1Service_1_1Cloudinary_1_1CloudinaryUploadResult.html", null ],
    [ "BackEncordados.Usuarios.Dto.ContactoPostRequestDto", "classBackEncordados_1_1Usuarios_1_1Dto_1_1ContactoPostRequestDto.html", null ],
    [ "TestEncordados.Unit.Infrastructure.CorsConfigTests", "classTestEncordados_1_1Unit_1_1Infrastructure_1_1CorsConfigTests.html", null ],
    [ "BackEncordados.Usuarios.Dto.CreateEncoderRequestDto", "classBackEncordados_1_1Usuarios_1_1Dto_1_1CreateEncoderRequestDto.html", null ],
    [ "TestEncordados.Unit.Common.Dto.CreateEncoderRequestDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1CreateEncoderRequestDtoTests.html", null ],
    [ "TestEncordados.Unit.Errors.CuerdaErrorTests", "classTestEncordados_1_1Unit_1_1Errors_1_1CuerdaErrorTests.html", null ],
    [ "BackEncordados.Materials.Dto.Strings.CuerdaPatchDto", "classBackEncordados_1_1Materials_1_1Dto_1_1Strings_1_1CuerdaPatchDto.html", null ],
    [ "TestEncordados.Unit.Validators.Cuerdas.CuerdaPatchValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Cuerdas_1_1CuerdaPatchValidatorTests.html", null ],
    [ "BackEncordados.Materials.Dto.Strings.CuerdaRequestDto", "classBackEncordados_1_1Materials_1_1Dto_1_1Strings_1_1CuerdaRequestDto.html", null ],
    [ "TestEncordados.Unit.Validators.Cuerdas.CuerdaRequestValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Cuerdas_1_1CuerdaRequestValidatorTests.html", null ],
    [ "TestEncordados.Unit.Validators.Materials.CuerdaRequestValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Materials_1_1CuerdaRequestValidatorTests.html", null ],
    [ "TestEncordados.Unit.Common.Dto.CuerdaResponseDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1CuerdaResponseDtoTests.html", null ],
    [ "TestEncordados.Unit.Controllers.Cuerdas.CuerdasControllerTests", "classTestEncordados_1_1Unit_1_1Controllers_1_1Cuerdas_1_1CuerdasControllerTests.html", null ],
    [ "TestEncordados.Integration.Repositories.CuerdasRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1CuerdasRepositoryTests.html", null ],
    [ "TestEncordados.Unit.Services.MaterialsService.CuerdasServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1MaterialsService_1_1CuerdasServiceTests.html", null ],
    [ "DbContext", null, [
      [ "TestEncordados.Unit.Common.Database.NonTimestampedContext", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1NonTimestampedContext.html", null ],
      [ "TestEncordados.Unit.Common.Database.TimestampTestContext", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1TimestampTestContext.html", null ],
      [ "TestEncordados.Unit.Common.Database.VersionTestContext", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1VersionTestContext.html", null ],
      [ "TestEncordados.Unit.Filters.SecondTestDbContext", "classTestEncordados_1_1Unit_1_1Filters_1_1SecondTestDbContext.html", null ],
      [ "TestEncordados.Unit.Filters.TestDbContext", "classTestEncordados_1_1Unit_1_1Filters_1_1TestDbContext.html", null ]
    ] ],
    [ "TestEncordados.Unit.Infrastructure.DiRegistrationTests", "classTestEncordados_1_1Unit_1_1Infrastructure_1_1DiRegistrationTests.html", null ],
    [ "TestEncordados.Unit.Errors.DomainErrorsTests", "classTestEncordados_1_1Unit_1_1Errors_1_1DomainErrorsTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Email.EmailBackgroundServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Email_1_1EmailBackgroundServiceTests.html", null ],
    [ "BackEncordados.Common.Service.Email.EmailMessage", "classBackEncordados_1_1Common_1_1Service_1_1Email_1_1EmailMessage.html", null ],
    [ "TestEncordados.Unit.Common.Service.Email.EmailMessageTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Email_1_1EmailMessageTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Email.EmailTemplatesTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Email_1_1EmailTemplatesTests.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelAdvancedDataDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelAdvancedDataDto.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelAdvancedRequestDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelAdvancedRequestDto.html", null ],
    [ "TestEncordados.Unit.Common.Dto.ExcelAdvancedRequestDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1ExcelAdvancedRequestDtoTests.html", null ],
    [ "TestEncordados.Integration.Excel.Archive.ExcelArchiveManagerTests", "classTestEncordados_1_1Integration_1_1Excel_1_1Archive_1_1ExcelArchiveManagerTests.html", null ],
    [ "TestEncordados.Unit.Excel.Controller.ExcelControllerTests", "classTestEncordados_1_1Unit_1_1Excel_1_1Controller_1_1ExcelControllerTests.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelCuerdasDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelCuerdasDto.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelImportResultDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelImportResultDto.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelMaterialsDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelMaterialsDto.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelPedidoLineasDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelPedidoLineasDto.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelPedidosDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelPedidosDto.html", null ],
    [ "TestEncordados.Integration.Repositories.ExcelRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1ExcelRepositoryTests.html", null ],
    [ "TestEncordados.Unit.Excel.Service.ExcelServiceTests", "classTestEncordados_1_1Unit_1_1Excel_1_1Service_1_1ExcelServiceTests.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelTournamentDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelTournamentDto.html", null ],
    [ "BackEncordados.Excel.Dto.ExcelUsersDto", "classBackEncordados_1_1Excel_1_1Dto_1_1ExcelUsersDto.html", null ],
    [ "Exception", null, [
      [ "BackEncordados.Common.Exceptions.CloudinaryException", "classBackEncordados_1_1Common_1_1Exceptions_1_1CloudinaryException.html", [
        [ "BackEncordados.Common.Exceptions.CloudinaryConfigurationException", "classBackEncordados_1_1Common_1_1Exceptions_1_1CloudinaryConfigurationException.html", null ],
        [ "BackEncordados.Common.Exceptions.CloudinaryDeleteException", "classBackEncordados_1_1Common_1_1Exceptions_1_1CloudinaryDeleteException.html", null ],
        [ "BackEncordados.Common.Exceptions.CloudinaryInvalidParameterException", "classBackEncordados_1_1Common_1_1Exceptions_1_1CloudinaryInvalidParameterException.html", null ],
        [ "BackEncordados.Common.Exceptions.CloudinaryUploadException", "classBackEncordados_1_1Common_1_1Exceptions_1_1CloudinaryUploadException.html", null ]
      ] ]
    ] ],
    [ "TestEncordados.Integration.Export.Archive.ExportArchiveManagerTests", "classTestEncordados_1_1Integration_1_1Export_1_1Archive_1_1ExportArchiveManagerTests.html", null ],
    [ "TestEncordados.Unit.Export.Controller.ExportControllerTests", "classTestEncordados_1_1Unit_1_1Export_1_1Controller_1_1ExportControllerTests.html", null ],
    [ "BackEncordados.Export.Dto.ExportDataDto", "classBackEncordados_1_1Export_1_1Dto_1_1ExportDataDto.html", null ],
    [ "BackEncordados.Common.Dto.ExportEntityInfo", "classBackEncordados_1_1Common_1_1Dto_1_1ExportEntityInfo.html", null ],
    [ "TestEncordados.Unit.Common.Dto.ExportEntityInfoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1ExportEntityInfoTests.html", null ],
    [ "BackEncordados.Common.Dto.ExportManifestDto", "classBackEncordados_1_1Common_1_1Dto_1_1ExportManifestDto.html", null ],
    [ "TestEncordados.Unit.Common.Dto.ExportManifestDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1ExportManifestDtoTests.html", null ],
    [ "TestEncordados.Integration.Repositories.ExportRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1ExportRepositoryTests.html", null ],
    [ "TestEncordados.Unit.Export.Service.ExportServiceTests", "classTestEncordados_1_1Unit_1_1Export_1_1Service_1_1ExportServiceTests.html", null ],
    [ "TestEncordados.Unit.Infrastructure.GlobalExceptionHandlerTests", "classTestEncordados_1_1Unit_1_1Infrastructure_1_1GlobalExceptionHandlerTests.html", null ],
    [ "TestEncordados.Unit.Middleware.GlobalExceptionHandlerTests", "classTestEncordados_1_1Unit_1_1Middleware_1_1GlobalExceptionHandlerTests.html", null ],
    [ "TestEncordados.Integration.Api.HealthEndpointTests", "classTestEncordados_1_1Integration_1_1Api_1_1HealthEndpointTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Cache.HybridCacheServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cache_1_1HybridCacheServiceTests.html", null ],
    [ "BackEncordados.Usuarios.Service.Auth.IAuthService", "interfaceBackEncordados_1_1Usuarios_1_1Service_1_1Auth_1_1IAuthService.html", null ],
    [ "BackEncordados.Common.Service.Cache.ICacheService", "interfaceBackEncordados_1_1Common_1_1Service_1_1Cache_1_1ICacheService.html", null ],
    [ "IClientProxy", null, [
      [ "TestEncordados.Unit.Services.Purchased.NoOpClientProxy", "classTestEncordados_1_1Unit_1_1Services_1_1Purchased_1_1NoOpClientProxy.html", null ]
    ] ],
    [ "BackEncordados.Common.Service.Cloudinary.ICloudinaryService", "interfaceBackEncordados_1_1Common_1_1Service_1_1Cloudinary_1_1ICloudinaryService.html", null ],
    [ "IDesignTimeDbContextFactory", null, [
      [ "BackEncordados.Infraestructure.Migrations.MaterialsDbContextFactory", "classBackEncordados_1_1Infraestructure_1_1Migrations_1_1MaterialsDbContextFactory.html", null ],
      [ "BackEncordados.Infraestructure.Migrations.UserDbContextFactory", "classBackEncordados_1_1Infraestructure_1_1Migrations_1_1UserDbContextFactory.html", null ]
    ] ],
    [ "BackEncordados.Common.Service.Email.IEmailService", "interfaceBackEncordados_1_1Common_1_1Service_1_1Email_1_1IEmailService.html", [
      [ "BackEncordados.Common.Service.Email.MemoryEmailService", "classBackEncordados_1_1Common_1_1Service_1_1Email_1_1MemoryEmailService.html", null ]
    ] ],
    [ "BackEncordados.Excel.Archive.IExcelArchiveManager", "interfaceBackEncordados_1_1Excel_1_1Archive_1_1IExcelArchiveManager.html", [
      [ "BackEncordados.Excel.Archive.ExcelArchiveManager", "classBackEncordados_1_1Excel_1_1Archive_1_1ExcelArchiveManager.html", null ]
    ] ],
    [ "BackEncordados.Excel.Repository.IExcelRepository", "interfaceBackEncordados_1_1Excel_1_1Repository_1_1IExcelRepository.html", null ],
    [ "BackEncordados.Excel.Service.IExcelService", "interfaceBackEncordados_1_1Excel_1_1Service_1_1IExcelService.html", null ],
    [ "BackEncordados.Export.Archive.IExportArchiveManager", "interfaceBackEncordados_1_1Export_1_1Archive_1_1IExportArchiveManager.html", null ],
    [ "BackEncordados.Export.Repository.IExportRepository", "interfaceBackEncordados_1_1Export_1_1Repository_1_1IExportRepository.html", null ],
    [ "BackEncordados.Export.Service.IExportService", "interfaceBackEncordados_1_1Export_1_1Service_1_1IExportService.html", null ],
    [ "BackEncordados.Usuarios.Service.Auth.IJwtService", "interfaceBackEncordados_1_1Usuarios_1_1Service_1_1Auth_1_1IJwtService.html", null ],
    [ "BackEncordados.Usuarios.Service.Auth.IJwtTokenExtractor", "interfaceBackEncordados_1_1Usuarios_1_1Service_1_1Auth_1_1IJwtTokenExtractor.html", [
      [ "BackEncordados.Usuarios.Service.Auth.JwtTokenExtractor", "classBackEncordados_1_1Usuarios_1_1Service_1_1Auth_1_1JwtTokenExtractor.html", null ]
    ] ],
    [ "BackEncordados.Excel.Repository.IMaterialsExcelRepository", "interfaceBackEncordados_1_1Excel_1_1Repository_1_1IMaterialsExcelRepository.html", null ],
    [ "BackEncordados.Export.Repository.IMaterialsExportRepository", "interfaceBackEncordados_1_1Export_1_1Repository_1_1IMaterialsExportRepository.html", null ],
    [ "BackEncordados.Excel.Repository.IPedidosExcelRepository", "interfaceBackEncordados_1_1Excel_1_1Repository_1_1IPedidosExcelRepository.html", null ],
    [ "BackEncordados.Export.Repository.IPedidosExportRepository", "interfaceBackEncordados_1_1Export_1_1Repository_1_1IPedidosExportRepository.html", null ],
    [ "BackEncordados.Materials.Repository.IProductsRepository< T, F >", "interfaceBackEncordados_1_1Materials_1_1Repository_1_1IProductsRepository.html", null ],
    [ "BackEncordados.Materials.Repository.IProductsRepository< Cuerdas, CuerdaFilterdto >", "interfaceBackEncordados_1_1Materials_1_1Repository_1_1IProductsRepository.html", [
      [ "BackEncordados.Materials.Repository.Strings.ICuerdasRepository", "interfaceBackEncordados_1_1Materials_1_1Repository_1_1Strings_1_1ICuerdasRepository.html", null ]
    ] ],
    [ "BackEncordados.Materials.Service.Common.IProductsService< T, E, R, P, F >", "interfaceBackEncordados_1_1Materials_1_1Service_1_1Common_1_1IProductsService.html", null ],
    [ "BackEncordados.Purchased.Repository.IPuchasedRepository", "interfaceBackEncordados_1_1Purchased_1_1Repository_1_1IPuchasedRepository.html", null ],
    [ "BackEncordados.Purchased.Service.IPurchasedService", "interfaceBackEncordados_1_1Purchased_1_1Service_1_1IPurchasedService.html", null ],
    [ "IRouteConstraint", null, [
      [ "BackEncordados.Infraestructure.Constraints.UlidRouteConstraint", "classBackEncordados_1_1Infraestructure_1_1Constraints_1_1UlidRouteConstraint.html", null ]
    ] ],
    [ "BackEncordados.Excel.Repository.ITalleresExcelRepository", "interfaceBackEncordados_1_1Excel_1_1Repository_1_1ITalleresExcelRepository.html", null ],
    [ "BackEncordados.Export.Repository.ITalleresExportRepository", "interfaceBackEncordados_1_1Export_1_1Repository_1_1ITalleresExportRepository.html", null ],
    [ "BackEncordados.Common.Database.Helpers.ITimestamped", "interfaceBackEncordados_1_1Common_1_1Database_1_1Helpers_1_1ITimestamped.html", [
      [ "BackEncordados.Materials.Model.Cuerdas", "classBackEncordados_1_1Materials_1_1Model_1_1Cuerdas.html", null ],
      [ "BackEncordados.Materials.Model.Material", "classBackEncordados_1_1Materials_1_1Model_1_1Material.html", null ],
      [ "BackEncordados.Purchased.Model.PedidoLinea", "classBackEncordados_1_1Purchased_1_1Model_1_1PedidoLinea.html", null ],
      [ "BackEncordados.Purchased.Model.Pedidos", "classBackEncordados_1_1Purchased_1_1Model_1_1Pedidos.html", null ],
      [ "BackEncordados.Usuarios.Model.User", "classBackEncordados_1_1Usuarios_1_1Model_1_1User.html", null ]
    ] ],
    [ "BackEncordados.Talleres.Repository.ITournamentRepository", "interfaceBackEncordados_1_1Talleres_1_1Repository_1_1ITournamentRepository.html", null ],
    [ "BackEncordados.Talleres.Service.ITournamentService", "interfaceBackEncordados_1_1Talleres_1_1Service_1_1ITournamentService.html", null ],
    [ "BackEncordados.Excel.Repository.IUserExcelRepository", "interfaceBackEncordados_1_1Excel_1_1Repository_1_1IUserExcelRepository.html", null ],
    [ "BackEncordados.Export.Repository.IUserExportRepository", "interfaceBackEncordados_1_1Export_1_1Repository_1_1IUserExportRepository.html", null ],
    [ "BackEncordados.Usuarios.Repository.IUserRepository", "interfaceBackEncordados_1_1Usuarios_1_1Repository_1_1IUserRepository.html", null ],
    [ "BackEncordados.Usuarios.Service.CrudService.IUserService", "interfaceBackEncordados_1_1Usuarios_1_1Service_1_1CrudService_1_1IUserService.html", null ],
    [ "BackEncordados.Common.Service.WhatsApp.IWhatsAppService", "interfaceBackEncordados_1_1Common_1_1Service_1_1WhatsApp_1_1IWhatsAppService.html", [
      [ "BackEncordados.Common.Service.WhatsApp.WhatsAppService", "classBackEncordados_1_1Common_1_1Service_1_1WhatsApp_1_1WhatsAppService.html", null ]
    ] ],
    [ "TestEncordados.Unit.Services.AuthService.JwtServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1AuthService_1_1JwtServiceTests.html", null ],
    [ "TestEncordados.Unit.Services.AuthService.JwtTokenExtractorTests", "classTestEncordados_1_1Unit_1_1Services_1_1AuthService_1_1JwtTokenExtractorTests.html", null ],
    [ "TestEncordados.Integration.Email.MailKitEmailServiceTests", "classTestEncordados_1_1Integration_1_1Email_1_1MailKitEmailServiceTests.html", null ],
    [ "TestEncordados.Unit.Errors.MaterialErrorTests", "classTestEncordados_1_1Unit_1_1Errors_1_1MaterialErrorTests.html", null ],
    [ "TestEncordados.Unit.Mappers.MaterialMapperTests", "classTestEncordados_1_1Unit_1_1Mappers_1_1MaterialMapperTests.html", null ],
    [ "BackEncordados.Materials.Dto.Materials.MaterialPatchDto", "classBackEncordados_1_1Materials_1_1Dto_1_1Materials_1_1MaterialPatchDto.html", null ],
    [ "TestEncordados.Unit.Validators.Materials.MaterialPatchValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Materials_1_1MaterialPatchValidatorTests.html", null ],
    [ "BackEncordados.Materials.Dto.Materials.MaterialRequestDto", "classBackEncordados_1_1Materials_1_1Dto_1_1Materials_1_1MaterialRequestDto.html", null ],
    [ "TestEncordados.Unit.Validators.Materials.MaterialRequestValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Materials_1_1MaterialRequestValidatorTests.html", null ],
    [ "TestEncordados.Unit.Controllers.Materials.MaterialsControllerTests", "classTestEncordados_1_1Unit_1_1Controllers_1_1Materials_1_1MaterialsControllerTests.html", null ],
    [ "TestEncordados.Integration.Repositories.MaterialsRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1MaterialsRepositoryTests.html", null ],
    [ "TestEncordados.Unit.Services.MaterialsService.MaterialsServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1MaterialsService_1_1MaterialsServiceTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Cache.MemoryCacheServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cache_1_1MemoryCacheServiceTests.html", null ],
    [ "TestEncordados.Unit.Common.Service.Email.MemoryEmailServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Email_1_1MemoryEmailServiceTests.html", null ],
    [ "Migration", null, [
      [ "BackEncordados.Migrations.Materials.AddUniqueIndexesMaterialsAndCuerdas", "classBackEncordados_1_1Migrations_1_1Materials_1_1AddUniqueIndexesMaterialsAndCuerdas.html", null ],
      [ "BackEncordados.Migrations.Materials.DropUniqueIndexesMaterialsAndCuerdas", "classBackEncordados_1_1Migrations_1_1Materials_1_1DropUniqueIndexesMaterialsAndCuerdas.html", null ],
      [ "BackEncordados.Migrations.Materials.FixIdentitySequences", "classBackEncordados_1_1Migrations_1_1Materials_1_1FixIdentitySequences.html", null ],
      [ "BackEncordados.Migrations.Materials.InitialCreate", "classBackEncordados_1_1Migrations_1_1Materials_1_1InitialCreate.html", null ],
      [ "BackEncordados.Migrations.User.InitialCreate", "classBackEncordados_1_1Migrations_1_1User_1_1InitialCreate.html", null ]
    ] ],
    [ "ModelSnapshot", null, [
      [ "BackEncordados.Migrations.Materials.MaterialsDbContextModelSnapshot", "classBackEncordados_1_1Migrations_1_1Materials_1_1MaterialsDbContextModelSnapshot.html", null ],
      [ "BackEncordados.Migrations.User.UserDbContextModelSnapshot", "classBackEncordados_1_1Migrations_1_1User_1_1UserDbContextModelSnapshot.html", null ]
    ] ],
    [ "TestEncordados.Unit.Common.Database.NonTimestampedEntity", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1NonTimestampedEntity.html", null ],
    [ "TestEncordados.Unit.Common.Service.Email.OrderItemEmailDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Email_1_1OrderItemEmailDtoTests.html", null ],
    [ "TestEncordados.Unit.Common.Dto.PageResponseDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1PageResponseDtoTests.html", null ],
    [ "BackEncordados.Purchased.Dto.PedidoLineaPatchDto", "classBackEncordados_1_1Purchased_1_1Dto_1_1PedidoLineaPatchDto.html", null ],
    [ "BackEncordados.Purchased.Dto.PedidoLineaRequestDto", "classBackEncordados_1_1Purchased_1_1Dto_1_1PedidoLineaRequestDto.html", null ],
    [ "TestEncordados.Unit.Common.Dto.PedidoLineaResponseDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1PedidoLineaResponseDtoTests.html", null ],
    [ "TestEncordados.Unit.Validators.Purchased.PedidoLineaValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1PedidoLineaValidatorTests.html", null ],
    [ "TestEncordados.Integration.Fixtures.PostgreSqlTestBase", "classTestEncordados_1_1Integration_1_1Fixtures_1_1PostgreSqlTestBase.html", [
      [ "TestEncordados.Integration.Fixtures.MaterialsDatabaseFixture", "classTestEncordados_1_1Integration_1_1Fixtures_1_1MaterialsDatabaseFixture.html", null ],
      [ "TestEncordados.Integration.Fixtures.UserDatabaseFixture", "classTestEncordados_1_1Integration_1_1Fixtures_1_1UserDatabaseFixture.html", null ]
    ] ],
    [ "TestEncordados.Unit.Controllers.Purchased.PurchasedControllerTests", "classTestEncordados_1_1Unit_1_1Controllers_1_1Purchased_1_1PurchasedControllerTests.html", null ],
    [ "TestEncordados.Unit.Errors.PurchasedErrorsTests", "classTestEncordados_1_1Unit_1_1Errors_1_1PurchasedErrorsTests.html", null ],
    [ "TestEncordados.Unit.Mappers.PurchasedMapperTests", "classTestEncordados_1_1Unit_1_1Mappers_1_1PurchasedMapperTests.html", null ],
    [ "TestEncordados.Unit.Validators.Purchased.PurchasedPatchValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1PurchasedPatchValidatorTests.html", null ],
    [ "TestEncordados.Integration.Repositories.PurchasedRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1PurchasedRepositoryTests.html", null ],
    [ "BackEncordados.Purchased.Dto.PurchasedRequestDto", "classBackEncordados_1_1Purchased_1_1Dto_1_1PurchasedRequestDto.html", null ],
    [ "TestEncordados.Unit.Validators.Purchased.PurchasedRequestValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1PurchasedRequestValidatorTests.html", null ],
    [ "TestEncordados.Unit.Common.Dto.PurchasedResponseDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1PurchasedResponseDtoTests.html", null ],
    [ "TestEncordados.Unit.Services.Purchased.PurchasedServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1Purchased_1_1PurchasedServiceTests.html", null ],
    [ "SaveChangesInterceptor", null, [
      [ "BackEncordados.Common.Database.Config.VersionInterceptor", "classBackEncordados_1_1Common_1_1Database_1_1Config_1_1VersionInterceptor.html", null ],
      [ "BackEncordados.Common.Database.Helpers.TimestampInterceptor", "classBackEncordados_1_1Common_1_1Database_1_1Helpers_1_1TimestampInterceptor.html", null ]
    ] ],
    [ "TestEncordados.Unit.Infrastructure.SerilogConfigTests", "classTestEncordados_1_1Unit_1_1Infrastructure_1_1SerilogConfigTests.html", null ],
    [ "TestEncordados.Unit.Common.SignalR.SignalHubTests", "classTestEncordados_1_1Unit_1_1Common_1_1SignalR_1_1SignalHubTests.html", null ],
    [ "BackEncordados.Purchased.Model.StringSetup", "classBackEncordados_1_1Purchased_1_1Model_1_1StringSetup.html", null ],
    [ "BackEncordados.Purchased.Dto.StringSetupDto", "classBackEncordados_1_1Purchased_1_1Dto_1_1StringSetupDto.html", null ],
    [ "TestEncordados.Unit.Validators.Purchased.StringSetupPatchValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1StringSetupPatchValidatorTests.html", null ],
    [ "TestEncordados.Unit.Validators.Purchased.StringSetupRequestValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1StringSetupRequestValidatorTests.html", null ],
    [ "BackEncordados.Talleres.Dto.SupervisorAsignmentRequestDto", "classBackEncordados_1_1Talleres_1_1Dto_1_1SupervisorAsignmentRequestDto.html", null ],
    [ "TestEncordados.Unit.Common.Database.TimestampInterceptorTests", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1TimestampInterceptorTests.html", null ],
    [ "BackEncordados.Talleres.Dto.TournamentAdminRequestDto", "classBackEncordados_1_1Talleres_1_1Dto_1_1TournamentAdminRequestDto.html", null ],
    [ "BackEncordados.Excel.Dto.TournamentExcelRowDto", "classBackEncordados_1_1Excel_1_1Dto_1_1TournamentExcelRowDto.html", null ],
    [ "BackEncordados.Talleres.Dto.TournamentPatchDto", "classBackEncordados_1_1Talleres_1_1Dto_1_1TournamentPatchDto.html", null ],
    [ "TestEncordados.Integration.Repositories.TournamentRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1TournamentRepositoryTests.html", null ],
    [ "BackEncordados.Talleres.Dto.TournamentRequestDto", "classBackEncordados_1_1Talleres_1_1Dto_1_1TournamentRequestDto.html", null ],
    [ "TestEncordados.Unit.Common.Dto.TournamentResponseDetailsDtoTests", "classTestEncordados_1_1Unit_1_1Common_1_1Dto_1_1TournamentResponseDetailsDtoTests.html", null ],
    [ "TestEncordados.Unit.Controllers.Talleres.TournamentsControllerTests", "classTestEncordados_1_1Unit_1_1Controllers_1_1Talleres_1_1TournamentsControllerTests.html", null ],
    [ "TestEncordados.Unit.Errors.TournamentsErrorsTests", "classTestEncordados_1_1Unit_1_1Errors_1_1TournamentsErrorsTests.html", null ],
    [ "TestEncordados.Unit.Services.Talleres.TournamentServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1Talleres_1_1TournamentServiceTests.html", null ],
    [ "TestEncordados.Unit.Mappers.TournamentsMapperTests", "classTestEncordados_1_1Unit_1_1Mappers_1_1TournamentsMapperTests.html", null ],
    [ "TestEncordados.Unit.Filters.TransactionalAttributeTests", "classTestEncordados_1_1Unit_1_1Filters_1_1TransactionalAttributeTests.html", null ],
    [ "TestEncordados.Unit.Infrastructure.UlidRouteConstraintTests", "classTestEncordados_1_1Unit_1_1Infrastructure_1_1UlidRouteConstraintTests.html", null ],
    [ "TestEncordados.Unit.Common.Database.UlidToStringConverterTests", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1UlidToStringConverterTests.html", null ],
    [ "BackEncordados.Common.Utils.Unit", "structBackEncordados_1_1Common_1_1Utils_1_1Unit.html", null ],
    [ "TestEncordados.UserControllerTests", "classTestEncordados_1_1UserControllerTests.html", null ],
    [ "TestEncordados.Unit.Mappers.UserMapperTests", "classTestEncordados_1_1Unit_1_1Mappers_1_1UserMapperTests.html", null ],
    [ "TestEncordados.Integration.Repositories.UserRepositoryTests", "classTestEncordados_1_1Integration_1_1Repositories_1_1UserRepositoryTests.html", null ],
    [ "BackEncordados.Usuarios.Dto.UserRequestDto", "classBackEncordados_1_1Usuarios_1_1Dto_1_1UserRequestDto.html", null ],
    [ "TestEncordados.Unit.Validators.Usuarios.UserRequestDtoValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Usuarios_1_1UserRequestDtoValidatorTests.html", null ],
    [ "BackEncordados.Usuarios.Model.User.UserRoles", "classBackEncordados_1_1Usuarios_1_1Model_1_1User_1_1UserRoles.html", null ],
    [ "TestEncordados.Unit.Services.Usuarios.UserServiceTests", "classTestEncordados_1_1Unit_1_1Services_1_1Usuarios_1_1UserServiceTests.html", null ],
    [ "ValueConverter", null, [
      [ "BackEncordados.Common.Database.Helpers.UlidToStringConverter", "classBackEncordados_1_1Common_1_1Database_1_1Helpers_1_1UlidToStringConverter.html", null ],
      [ "BackEncordados.Common.Database.Helpers.UlidToStringConverterNonNullable", "classBackEncordados_1_1Common_1_1Database_1_1Helpers_1_1UlidToStringConverterNonNullable.html", null ]
    ] ],
    [ "ValueGenerator", null, [
      [ "BackEncordados.Common.Database.Helpers.UlidValueGenerator", "classBackEncordados_1_1Common_1_1Database_1_1Helpers_1_1UlidValueGenerator.html", null ]
    ] ],
    [ "TestEncordados.Unit.Common.Database.VersionInterceptorTests", "classTestEncordados_1_1Unit_1_1Common_1_1Database_1_1VersionInterceptorTests.html", null ],
    [ "WebApplicationFactory", null, [
      [ "TestEncordados.Integration.Api.CustomWebApplicationFactory", "classTestEncordados_1_1Integration_1_1Api_1_1CustomWebApplicationFactory.html", null ]
    ] ],
    [ "TestEncordados.Unit.Common.Service.WhatsApp.WhatsAppServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1WhatsApp_1_1WhatsAppServiceTests.html", null ],
    [ "BackEncordados.Talleres.Dto.WorkerMachineAssignmentRequestDto", "classBackEncordados_1_1Talleres_1_1Dto_1_1WorkerMachineAssignmentRequestDto.html", null ]
];