var namespaceTestEncordados_1_1Unit_1_1Controllers_1_1Materials =
[
    [ "MaterialsControllerTests", "classTestEncordados_1_1Unit_1_1Controllers_1_1Materials_1_1MaterialsControllerTests.html", "classTestEncordados_1_1Unit_1_1Controllers_1_1Materials_1_1MaterialsControllerTests" ]
];