var namespaceTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cloudinary =
[
    [ "CloudinaryServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cloudinary_1_1CloudinaryServiceTests.html", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1Cloudinary_1_1CloudinaryServiceTests" ]
];