var namespaceTestEncordados_1_1Unit_1_1Common_1_1Service_1_1WhatsApp =
[
    [ "WhatsAppServiceTests", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1WhatsApp_1_1WhatsAppServiceTests.html", "classTestEncordados_1_1Unit_1_1Common_1_1Service_1_1WhatsApp_1_1WhatsAppServiceTests" ]
];