var namespaceBackEncordados_1_1Materials_1_1Validator_1_1Materials =
[
    [ "MaterialPatchValidator", "classBackEncordados_1_1Materials_1_1Validator_1_1Materials_1_1MaterialPatchValidator.html", "classBackEncordados_1_1Materials_1_1Validator_1_1Materials_1_1MaterialPatchValidator" ],
    [ "MaterialRequestValidator", "classBackEncordados_1_1Materials_1_1Validator_1_1Materials_1_1MaterialRequestValidator.html", "classBackEncordados_1_1Materials_1_1Validator_1_1Materials_1_1MaterialRequestValidator" ]
];