var StringSetupRequestValidatorTests_8cs =
[
    [ "TestEncordados.Unit.Validators.Purchased.StringSetupRequestValidatorTests", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1StringSetupRequestValidatorTests.html", "classTestEncordados_1_1Unit_1_1Validators_1_1Purchased_1_1StringSetupRequestValidatorTests" ]
];